### ISSUE TITLE
/bin/sh: 1: ./download_model.sh: not found

### ISSUE THREAD

**Issue by Mpal7** [RasaHQ/paraphraser#16]
Hello everyone i'm having issues with building the dockerfile, i'm new to docker but it seems like it can't find the `download_model.sh`, here's the error:

```#10 [ 6/13] RUN /home/download_model.sh  
#10 sha256:94d3f967690340f8c35c43a1702fb522b42c465dd3f39622a5548afc2aac5b2c  
#10 0.470 /bin/sh: 1: /home/download_model.sh: not found  
#10 ERROR: executor failed running [/bin/sh -c /home/download_model.sh]: exit code: 127 
```
i think the problem lies in this section of the dockerfile:
```
  WORKDIR /home

  COPY download_model.sh download_model.sh
  RUN ./download_model.sh
```
I thought about adding this command in the dockerfile `RUN dir`:  
```
  WORKDIR /home
  
  COPY download_model.sh download_model.sh
  RUN dir
  RUN ./download_model.sh
```
printing the following:
```
#10 [ 6/14] RUN dir
#10 sha256:3897e950f0add18c4f3eb3d7beba427134c711ea110c040575accdf1feddf627
#10 0.527 download_model.sh
#10 DONE 0.6s
```
is this print refering to what's inside /home in the image? if so download_model.sh should be there, than why it's not finding it when running the command  `RUN ./download_model.sh` ?

thanks

**Comment by eljbutler** [comment]
I seem to be getting this exact same issue. Did you find a resolution to this?

**Comment by Mpal7** [comment]
I wish, i also asked a [question ](https://stackoverflow.com/questions/74179054/dockerfile-build-run-file-not-found?noredirect=1#comment130968122_74179054) on github, someone commented that it might have something to do with line endings, but didn't have any luck.  
Please let me know if you find a way to make this work.
Thank you!

**Comment by eyal7773** [comment]
I solve it by change the Dockerfile.cpu to this.
Please be aware to run ./download_model.sh BEFORE building the dockerfile - according to [this](https://github.com/RasaHQ/paraphraser/issues/15#issuecomment-1142391240) comment.

```
FROM ubuntu:20.04

RUN apt-get update -qq \
    && apt-get install -y --no-install-recommends \
      wget \
      build-essential \
      curl \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN wget --no-check-certificate -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.3-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash miniconda.sh -b \
    && rm -f miniconda.sh

ENV PATH="/root/miniconda3/bin:${PATH}"

WORKDIR /home

COPY download_model.sh download_model.sh
RUN /bin/bash /home/download_model.sh

RUN conda install pytorch==1.4.0 torchvision==0.5.0 cpuonly -c pytorch

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY m39v1.tar ./
RUN tar -xvf m39v1.tar && rm -f m39v1.tar

COPY src src/
COPY test_bin test_bin/
COPY run_paraphraser.py run_paraphraser.py

ENTRYPOINT ["python", "run_paraphraser.py"]


```

**Comment by Mpal7** [comment]
Thank you @eyal7773 , i still don't understand why it's not working but i just downloaded manually the `m39v1.tar` and commented out the lines:
```
COPY download_model.sh download_model.sh
RUN /bin/bash /home/download_model.sh
```  
The problem now is that i'm unable to go through `RUN conda install pytorch==1.4.0 torchvision==0.5.0 cpuonly -c pytorch`, it throws some generic http error which i don't know how to debug, could be some broken dependencies maybe?  
```
 > [ 6/13] RUN conda install pytorch==1.4.0 torchvision==0.5.0 cpuonly -c pytorch:
#9 0.721 Collecting package metadata (current_repodata.json): ...working... failed
#9 7.178
#9 7.178 CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/linux-64/current_repodata.json>
#9 7.178 Elapsed: -
#9 7.178
#9 7.178 An HTTP error occurred when trying to retrieve this URL.
#9 7.178 HTTP errors are often intermittent, and a simple retry will get you on your way.
#9 7.178
#9 7.178 If your current network has https://www.anaconda.com blocked, please file
#9 7.178 a support request with your network engineering team.
#9 7.178
#9 7.178 'https://repo.anaconda.com/pkgs/main/linux-64'
#9 7.178
#9 7.178
```  
Did you have the same problem by any chances? i can reach `<https://repo.anaconda.com/pkgs/main/linux-64/current_repodata.json> `without a problem from my machine, could there be some problems from inside the docker?

**Comment by eyal7773** [comment]
No, for me it just works fine

**Comment by eljbutler** [comment]
Applying the above resolved it for me too. Thanks @eyal7773!
